baseURL = "https://bergmannf.github.io/"
languageCode = "en-us"
title = "Personal blog"
copyright = "This is a customized copyright."
theme = "hyde-hyde"

[params]
    author = "Florian Bergmann"
    title = "My personal blog"
    authorimage = "/img/avatar.png"

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "bergmannf"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"