languageCode = "en-us"

baseurl = "https://blog.niflheim.cc/"
title = "Personal blog"

theme = "PaperMod"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    style = "monokai"
    tabWidth = 4

ignoreFiles = [ "\\.org" ]

disqusShortname = "nifl-blog"
googleAnalytics = "UA-165940833-1"

[params]
    author = "Florian Bergmann"
    avatarurl = "img/avatar.png"

    description = "My personal blog"
    keywords = ["blog", "developer", "personal"]
    info = ""
    #gravatar = "john.doe@example.com"
    footercontent = "All opinions expressed here are solely my own."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []
    ShowRssButtonInSectionTermList = true

    [params.assets]
        disableHLJS = true

    [params.homeInfoParams]
        Title = "Information"
        Content = "These are just some notes and posts I write to share information. All opinions stated in these posts are solely my own."


    [[params.socialIcons]]
        name = "Github"
        title = "Github"
        url = "https://github.com/bergmannf/"
    [[params.socialIcons]]
        name = "gitlab"
        url = "https://gitlab.com/bergmannf/"
    [[params.socialIcons]]
        name = "stackoverflow"
        url = "https://stackoverflow.com/users/247675/bergmannf"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/florian-bergmann-479b6888/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"
